### ISSUE TITLE
How to reflow after dynamically adding an item to the list

### ISSUE THREAD

**Issue by rbjarnason** [PolymerLabs/uni-virtualizer#75] opened 2020-09-25 12:49 UTC
We're using the better-grid branch and when adding a new item to a list that is on the screen, the item appears but the items are not flowing correctly - see image below. By resizing the browser the items snap into the correct flow and we've tried all APIs on the LitVirtualizer and the .layout (Layout1d) but none work - any ideas or is the API for this currently missing? On iron-list we used to fire an iron-resize event to fix exactly the same problem there, back in 2015 ;)

![image](https://user-images.githubusercontent.com/43699/94268935-71700780-ff2d-11ea-9663-f1e3b87e2a7a.png)

**Comment by graynorton** [comment] 2020-10-29 18:30
@rbjarnason Sorry for the slow response–I hadn't noticed this come in. Assuming that it reproduces easily, this looks like a bug to me; the intention is that you shouldn't need to do anything other than mutate the data and reassign the items array.

Would it be possible to create a simple repro case (Stackblitz, Codepen, a repo I can clone, or even a Gist)?

**Comment by thetaPC** [comment] 2020-11-02 20:55
@graynorton this appears to be a similar issue that I'm running into with a private project. I'm using expandable cards. There will be moments that when I expand a card, the list does not update the absolute positioning.

Is there a way to refresh/repaint the virtualizer? The function that does the calculations is private.

**Comment by graynorton** [comment] 2020-11-02 21:09
@thetaPC Are you using the `better-grid` branch, or `master`, or the latest pre-release from npm?

**Comment by thetaPC** [comment] 2020-11-02 21:11
@graynorton pre-release from npm

**Comment by thetaPC** [comment] 2020-11-02 21:18
@graynorton another issue that I'm encountering that is also part of the re-render. When a card is open (let's say the first one in the list) then the first card in the next viewport will be opened after scrolling. You can see the same issue being applied in the [demo page](https://polymerlabs.github.io/uni-virtualizer/basic-lit-element/).

**Closed** 2022-06-01 23:58 UTC
